# SPDX-License-Identifier: AGPL-3.0-only
"""Structured PCAP analysis findings."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class AnalysisRunStatus(StrEnum):
    """Lifecycle states for a PCAP analysis run."""

    RUNNING = "running"
    COMPLETED = "completed"
    PARTIAL = "partial"
    FAILED = "failed"


class FindingSeverity(StrEnum):
    """Operator-facing finding severity."""

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class FindingKind(StrEnum):
    """Finding kinds generated by the Phase 2B filter library."""

    PROTOCOL_HIERARCHY = "protocol_hierarchy"
    CONVERSATIONS = "conversations"
    DEAUTH_BURSTS = "deauth_bursts"
    FILTER_FAILED = "filter_failed"


class AnalysisRun(BaseModel):
    """One execution of the curated PCAP filter library."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=128)
    pcap_id: str = Field(min_length=1, max_length=128)
    engagement_id: str = Field(min_length=1, max_length=128)
    actor_id: str = Field(min_length=1, max_length=128)
    status: AnalysisRunStatus
    finding_counts: dict[FindingKind, int] = Field(default_factory=dict)
    error: str | None = Field(default=None, max_length=200)
    started_at: datetime
    finished_at: datetime | None = None


class AnalysisSummaryResponse(BaseModel):
    """Analysis status response for one PCAP."""

    model_config = ConfigDict(extra="forbid")

    analysis: AnalysisRun | None
    finding_counts: dict[FindingKind, int] = Field(default_factory=dict)


class AnalysisStartResponse(BaseModel):
    """Accepted analysis response."""

    model_config = ConfigDict(extra="forbid")

    analysis_id: str


class ProtocolNode(BaseModel):
    """One protocol hierarchy row."""

    model_config = ConfigDict(extra="forbid")

    bytes: int = Field(ge=0)
    depth: int = Field(ge=0)
    frames: int = Field(ge=0)
    protocol: str = Field(min_length=1, max_length=80)


class ProtocolHierarchyEvidence(BaseModel):
    """Protocol hierarchy evidence."""

    model_config = ConfigDict(extra="forbid")

    protocols: list[ProtocolNode] = Field(default_factory=list)


class Conversation(BaseModel):
    """One top talker conversation."""

    model_config = ConfigDict(extra="forbid")

    bytes: int = Field(ge=0)
    frames: int = Field(ge=0)
    left: str = Field(min_length=1, max_length=128)
    right: str = Field(min_length=1, max_length=128)


class ConversationsEvidence(BaseModel):
    """Conversation evidence for WLAN and IP conversations."""

    model_config = ConfigDict(extra="forbid")

    conversations: list[Conversation] = Field(default_factory=list)


class DeauthBurst(BaseModel):
    """One detected deauthentication burst."""

    model_config = ConfigDict(extra="forbid")

    bssid: str = Field(min_length=1, max_length=32)
    count: int = Field(ge=0)
    first_seen_epoch: float = Field(ge=0.0)
    last_seen_epoch: float = Field(ge=0.0)


class DeauthBurstsEvidence(BaseModel):
    """Deauthentication burst evidence."""

    model_config = ConfigDict(extra="forbid")

    bursts: list[DeauthBurst] = Field(default_factory=list)
    threshold: int = Field(default=10, ge=1)
    window_seconds: int = Field(default=300, ge=1)


class FailedFindingEvidence(BaseModel):
    """Sanitized failed-filter evidence."""

    model_config = ConfigDict(extra="forbid")

    filter_name: str = Field(min_length=1, max_length=80)
    reason: str = Field(min_length=1, max_length=200)


FindingEvidence = (
    ProtocolHierarchyEvidence | ConversationsEvidence | DeauthBurstsEvidence | FailedFindingEvidence
)


class Finding(BaseModel):
    """Persisted structured PCAP finding."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=128)
    pcap_id: str = Field(min_length=1, max_length=128)
    engagement_id: str = Field(min_length=1, max_length=128)
    analysis_id: str = Field(min_length=1, max_length=128)
    kind: FindingKind
    severity: FindingSeverity
    summary: str = Field(min_length=1, max_length=200)
    evidence: FindingEvidence
    generated_at: datetime


class ProtocolHierarchyFinding(Finding):
    """Protocol hierarchy finding."""

    kind: Literal[FindingKind.PROTOCOL_HIERARCHY] = FindingKind.PROTOCOL_HIERARCHY
    evidence: ProtocolHierarchyEvidence


class ConversationsFinding(Finding):
    """Conversations finding."""

    kind: Literal[FindingKind.CONVERSATIONS] = FindingKind.CONVERSATIONS
    evidence: ConversationsEvidence


class DeauthBurstsFinding(Finding):
    """Deauthentication burst finding."""

    kind: Literal[FindingKind.DEAUTH_BURSTS] = FindingKind.DEAUTH_BURSTS
    evidence: DeauthBurstsEvidence


class FailedFinding(Finding):
    """Failed-filter placeholder finding."""

    kind: Literal[FindingKind.FILTER_FAILED] = FindingKind.FILTER_FAILED
    evidence: FailedFindingEvidence
