# SPDX-License-Identifier: AGPL-3.0-only
"""Structured PCAP analysis findings."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from cheeky_pony_backend.pcap.network_findings import (
    DhcpHostnamesEvidence,
    DnsSummaryEvidence,
    TlsSniSummaryEvidence,
)

JS_DATE_MAX_EPOCH_SECONDS = 8_640_000_000_000.0


class AnalysisRunStatus(StrEnum):
    """Lifecycle states for a PCAP analysis run."""

    RUNNING = "running"
    COMPLETED = "completed"
    PARTIAL = "partial"
    FAILED = "failed"


class FindingSeverity(StrEnum):
    """Operator-facing finding severity."""

    INFO = "info"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class FindingKind(StrEnum):
    """Finding kinds generated by the curated filter library."""

    PROTOCOL_HIERARCHY = "protocol_hierarchy"
    CONVERSATIONS = "conversations"
    DEAUTH_BURSTS = "deauth_bursts"
    EAPOL_HANDSHAKES = "eapol_handshakes"
    BEACONS = "beacons"
    PROBE_RESPONSE_ANOMALIES = "probe_response_anomalies"
    DNS_SUMMARY = "dns_summary"
    TLS_SNI_SUMMARY = "tls_sni_summary"
    DHCP_HOSTNAMES = "dhcp_hostnames"
    FILTER_FAILED = "filter_failed"


class AnalysisRun(BaseModel):
    """One execution of the curated PCAP filter library."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=128)
    pcap_id: str = Field(min_length=1, max_length=128)
    engagement_id: str = Field(min_length=1, max_length=128)
    actor_id: str = Field(min_length=1, max_length=128)
    status: AnalysisRunStatus
    finding_counts: dict[FindingKind, int] = Field(default_factory=dict)
    error: str | None = Field(default=None, max_length=200)
    started_at: datetime
    finished_at: datetime | None = None


class AnalysisSummaryResponse(BaseModel):
    """Analysis status response for one PCAP."""

    model_config = ConfigDict(extra="forbid")

    analysis: AnalysisRun | None
    finding_counts: dict[FindingKind, int] = Field(default_factory=dict)


class AnalysisStartResponse(BaseModel):
    """Accepted analysis response."""

    model_config = ConfigDict(extra="forbid")

    analysis_id: str


class ProtocolNode(BaseModel):
    """One protocol hierarchy row."""

    model_config = ConfigDict(extra="forbid")

    bytes: int = Field(ge=0)
    depth: int = Field(ge=0)
    frames: int = Field(ge=0)
    protocol: str = Field(min_length=1, max_length=80)


class ProtocolHierarchyEvidence(BaseModel):
    """Protocol hierarchy evidence."""

    model_config = ConfigDict(extra="forbid")

    protocols: list[ProtocolNode] = Field(default_factory=list)


class Conversation(BaseModel):
    """One top talker conversation."""

    model_config = ConfigDict(extra="forbid")

    bytes: int = Field(ge=0)
    frames: int = Field(ge=0)
    left: str = Field(min_length=1, max_length=128)
    right: str = Field(min_length=1, max_length=128)


class ConversationsEvidence(BaseModel):
    """Conversation evidence for WLAN and IP conversations."""

    model_config = ConfigDict(extra="forbid")

    conversations: list[Conversation] = Field(default_factory=list)


class DeauthBurst(BaseModel):
    """One detected deauthentication burst."""

    model_config = ConfigDict(extra="forbid")

    bssid: str = Field(min_length=1, max_length=32)
    count: int = Field(ge=0)
    first_seen_epoch: float = Field(
        ge=0.0,
        le=JS_DATE_MAX_EPOCH_SECONDS,
        allow_inf_nan=False,
    )
    last_seen_epoch: float = Field(
        ge=0.0,
        le=JS_DATE_MAX_EPOCH_SECONDS,
        allow_inf_nan=False,
    )


class DeauthBurstsEvidence(BaseModel):
    """Deauthentication burst evidence."""

    model_config = ConfigDict(extra="forbid")

    bursts: list[DeauthBurst] = Field(default_factory=list)
    threshold: int = Field(default=10, ge=1)
    window_seconds: int = Field(default=300, ge=1)


class EapolHandshake(BaseModel):
    """One grouped EAPOL four-way handshake observation."""

    model_config = ConfigDict(extra="forbid")

    bssid: str = Field(min_length=1, max_length=32)
    client_mac: str = Field(min_length=1, max_length=32)
    complete: bool
    message_count: int = Field(ge=0, le=4)
    message_numbers: list[int] = Field(default_factory=list, max_length=4)
    pmkid: str | None = Field(default=None, max_length=128)
    raw_bytes_b64: list[str] | None = Field(default=None, max_length=8)


class EapolHandshakesEvidence(BaseModel):
    """EAPOL handshake metadata evidence."""

    model_config = ConfigDict(extra="forbid")

    handshakes: list[EapolHandshake] = Field(default_factory=list)


class BeaconMismatch(BaseModel):
    """Mismatch between a beacon and stored AP metadata."""

    model_config = ConfigDict(extra="forbid")

    detail: str = Field(min_length=1, max_length=160)
    field: Literal["channel", "ssid"]
    observed: str = Field(min_length=1, max_length=128)
    stored: str = Field(min_length=1, max_length=128)


class BeaconNetwork(BaseModel):
    """One beaconing BSSID summary."""

    model_config = ConfigDict(extra="forbid")

    beacon_interval_tu: int | None = Field(default=None, ge=1, le=65535)
    bssid: str = Field(min_length=1, max_length=32)
    capabilities: list[str] = Field(default_factory=list, max_length=24)
    channel: int | None = Field(default=None, ge=1, le=196)
    mismatches: list[BeaconMismatch] = Field(default_factory=list)
    ssid: str | None = Field(default=None, max_length=128)
    vendor_ies: list[str] = Field(default_factory=list, max_length=24)


class BeaconsEvidence(BaseModel):
    """Beacon summary evidence."""

    model_config = ConfigDict(extra="forbid")

    networks: list[BeaconNetwork] = Field(default_factory=list)


class ProbeResponseAnomaly(BaseModel):
    """AP responding to SSIDs it does not beacon."""

    model_config = ConfigDict(extra="forbid")

    anomalous_ssids: list[str] = Field(default_factory=list, max_length=16)
    beaconed_ssids: list[str] = Field(default_factory=list, max_length=16)
    bssid: str = Field(min_length=1, max_length=32)
    response_count: int = Field(ge=1)


class ProbeResponseAnomaliesEvidence(BaseModel):
    """Probe-response anomaly evidence."""

    model_config = ConfigDict(extra="forbid")

    anomalies: list[ProbeResponseAnomaly] = Field(default_factory=list)


class FailedFindingEvidence(BaseModel):
    """Sanitized failed-filter evidence."""

    model_config = ConfigDict(extra="forbid")

    filter_name: str = Field(min_length=1, max_length=80)
    reason: str = Field(min_length=1, max_length=200)


FindingEvidence = (
    ProtocolHierarchyEvidence
    | ConversationsEvidence
    | DeauthBurstsEvidence
    | EapolHandshakesEvidence
    | BeaconsEvidence
    | ProbeResponseAnomaliesEvidence
    | DnsSummaryEvidence
    | TlsSniSummaryEvidence
    | DhcpHostnamesEvidence
    | FailedFindingEvidence
)


class Finding(BaseModel):
    """Persisted structured PCAP finding."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=128)
    pcap_id: str = Field(min_length=1, max_length=128)
    engagement_id: str = Field(min_length=1, max_length=128)
    analysis_id: str = Field(min_length=1, max_length=128)
    kind: FindingKind
    severity: FindingSeverity
    summary: str = Field(min_length=1, max_length=200)
    evidence: FindingEvidence
    generated_at: datetime


class ProtocolHierarchyFinding(Finding):
    """Protocol hierarchy finding."""

    kind: Literal[FindingKind.PROTOCOL_HIERARCHY] = FindingKind.PROTOCOL_HIERARCHY
    evidence: ProtocolHierarchyEvidence


class ConversationsFinding(Finding):
    """Conversations finding."""

    kind: Literal[FindingKind.CONVERSATIONS] = FindingKind.CONVERSATIONS
    evidence: ConversationsEvidence


class DeauthBurstsFinding(Finding):
    """Deauthentication burst finding."""

    kind: Literal[FindingKind.DEAUTH_BURSTS] = FindingKind.DEAUTH_BURSTS
    evidence: DeauthBurstsEvidence


class EapolHandshakesFinding(Finding):
    """EAPOL handshake finding."""

    kind: Literal[FindingKind.EAPOL_HANDSHAKES] = FindingKind.EAPOL_HANDSHAKES
    evidence: EapolHandshakesEvidence


class BeaconsFinding(Finding):
    """Beacon analysis finding."""

    kind: Literal[FindingKind.BEACONS] = FindingKind.BEACONS
    evidence: BeaconsEvidence


class ProbeResponseAnomaliesFinding(Finding):
    """Probe-response anomaly finding."""

    kind: Literal[FindingKind.PROBE_RESPONSE_ANOMALIES] = FindingKind.PROBE_RESPONSE_ANOMALIES
    evidence: ProbeResponseAnomaliesEvidence


class DnsSummaryFinding(Finding):
    """DNS query summary finding."""

    kind: Literal[FindingKind.DNS_SUMMARY] = FindingKind.DNS_SUMMARY
    evidence: DnsSummaryEvidence


class TlsSniSummaryFinding(Finding):
    """TLS SNI summary finding."""

    kind: Literal[FindingKind.TLS_SNI_SUMMARY] = FindingKind.TLS_SNI_SUMMARY
    evidence: TlsSniSummaryEvidence


class DhcpHostnamesFinding(Finding):
    """DHCP hostname finding."""

    kind: Literal[FindingKind.DHCP_HOSTNAMES] = FindingKind.DHCP_HOSTNAMES
    evidence: DhcpHostnamesEvidence


class FailedFinding(Finding):
    """Failed-filter placeholder finding."""

    kind: Literal[FindingKind.FILTER_FAILED] = FindingKind.FILTER_FAILED
    evidence: FailedFindingEvidence


def redact_lab_gated_evidence(finding: Finding, *, lab_mode: bool) -> Finding:
    """Remove lab-only evidence from a finding before API serialization."""

    if lab_mode or not isinstance(finding.evidence, EapolHandshakesEvidence):
        return finding
    evidence = EapolHandshakesEvidence(
        handshakes=[
            handshake.model_copy(update={"pmkid": None, "raw_bytes_b64": None})
            for handshake in finding.evidence.handshakes
        ]
    )
    return finding.model_copy(update={"evidence": evidence})
