/* Generated by scripts/generate-openapi-types.py. Do not edit manually. */
export interface components {
  schemas: {
    "AccessPoint": unknown;
    "AcknowledgementRequest": unknown;
    "Alert": unknown;
    "AlertRule": unknown;
    "AlertRuleCreateRequest": unknown;
    "AlertRuleUpdateRequest": unknown;
    "AlertSeverity": unknown;
    "AllowTargetRequest": unknown;
    "ApiPage_AccessPoint_": unknown;
    "ApiPage_AlertRule_": unknown;
    "ApiPage_Alert_": unknown;
    "ApiPage_AuditLog_": unknown;
    "ApiPage_Client_": unknown;
    "ApiPage_Event_": unknown;
    "ApiPage_Sensor_": unknown;
    "AuditLog": unknown;
    "Client": unknown;
    "Engagement": unknown;
    "EngagementCreateRequest": unknown;
    "Event": unknown;
    "EventKind": unknown;
    "HTTPValidationError": unknown;
    "LoginRequest": unknown;
    "LoginResponse": unknown;
    "RegisterRequest": unknown;
    "Sensor": unknown;
    "SensorCapability": unknown;
    "SensorRegisterRequest": unknown;
    "SensorRegisterResponse": unknown;
    "SignalSample": unknown;
    "SystemAcknowledgement": unknown;
    "TargetKind": unknown;
    "TotpSetupResponse": unknown;
    "TotpVerifyRequest": unknown;
    "UserPublic": unknown;
    "ValidationError": unknown;
  };
}

export interface paths {
  "/api/v1/access_points": Record<string, unknown>;
  "/api/v1/access_points/{bssid}": Record<string, unknown>;
  "/api/v1/access_points/{bssid}/clients": Record<string, unknown>;
  "/api/v1/alerts": Record<string, unknown>;
  "/api/v1/alerts/rules": Record<string, unknown>;
  "/api/v1/alerts/rules/{rule_id}": Record<string, unknown>;
  "/api/v1/alerts/{alert_id}/ack": Record<string, unknown>;
  "/api/v1/audit": Record<string, unknown>;
  "/api/v1/auth/2fa/setup": Record<string, unknown>;
  "/api/v1/auth/2fa/verify": Record<string, unknown>;
  "/api/v1/auth/login": Record<string, unknown>;
  "/api/v1/auth/logout": Record<string, unknown>;
  "/api/v1/auth/refresh": Record<string, unknown>;
  "/api/v1/auth/register": Record<string, unknown>;
  "/api/v1/devices": Record<string, unknown>;
  "/api/v1/devices/{mac}": Record<string, unknown>;
  "/api/v1/engagements": Record<string, unknown>;
  "/api/v1/engagements/{engagement_id}/allow-list": Record<string, unknown>;
  "/api/v1/events": Record<string, unknown>;
  "/api/v1/events/{event_id}": Record<string, unknown>;
  "/api/v1/sensors": Record<string, unknown>;
  "/api/v1/sensors/{sensor_id}": Record<string, unknown>;
  "/api/v1/sensors/{sensor_id}/revoke": Record<string, unknown>;
  "/api/v1/system/acknowledgements": Record<string, unknown>;
  "/health": Record<string, unknown>;
  "/metrics": Record<string, unknown>;
}
