/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access_points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Access Points
         * @description List observed access points.
         *
         *     Args:
         *         _: Current user.
         *         store: Application store.
         *         limit: Page size.
         *         offset: Page offset.
         *
         *     Returns:
         *         Paginated access point list.
         */
        get: operations["list_access_points_api_v1_access_points_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access_points/{bssid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Access Point
         * @description Return one access point.
         *
         *     Args:
         *         bssid: BSSID.
         *         _: Current user.
         *         store: Application store.
         *
         *     Returns:
         *         Access point.
         */
        get: operations["get_access_point_api_v1_access_points__bssid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access_points/{bssid}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Access Point Clients
         * @description List client devices associated with one access point.
         *
         *     Args:
         *         bssid: Access point BSSID.
         *         _: Current user.
         *         store: Application store.
         *         limit: Page size.
         *         offset: Page offset.
         *
         *     Returns:
         *         Paginated associated client list.
         */
        get: operations["list_access_point_clients_api_v1_access_points__bssid__clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description List alerts with severity and acknowledgement filters.
         *
         *     Args:
         *         _: Current user.
         *         store: Application store.
         *         severity: Optional repeated severity filter.
         *         acked: Optional acknowledgement-state filter.
         *         limit: Page size.
         *         offset: Page offset.
         *
         *     Returns:
         *         Paginated alert list.
         */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alert Rules
         * @description List alert rules.
         *
         *     Args:
         *         _: Current user.
         *         store: Application store.
         *         limit: Page size.
         *         offset: Page offset.
         *
         *     Returns:
         *         Paginated alert-rule list.
         */
        get: operations["list_alert_rules_api_v1_alerts_rules_get"];
        put?: never;
        /**
         * Create Alert Rule
         * @description Create an alert rule.
         *
         *     Args:
         *         payload: Rule payload.
         *         user: Current admin with verified TOTP.
         *         store: Application store.
         *         audit: Audit logger.
         *
         *     Returns:
         *         Created alert rule.
         */
        post: operations["create_alert_rule_api_v1_alerts_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Alert Rule
         * @description Delete an alert rule.
         *
         *     Args:
         *         rule_id: Alert rule identifier.
         *         user: Current admin with verified TOTP.
         *         store: Application store.
         *         audit: Audit logger.
         */
        delete: operations["delete_alert_rule_api_v1_alerts_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Alert Rule
         * @description Update an alert rule.
         *
         *     Args:
         *         rule_id: Alert rule identifier.
         *         payload: Rule update payload.
         *         user: Current admin with verified TOTP.
         *         store: Application store.
         *         audit: Audit logger.
         *
         *     Returns:
         *         Updated alert rule.
         */
        patch: operations["update_alert_rule_api_v1_alerts_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ack Alert
         * @description Acknowledge an alert.
         *
         *     Args:
         *         alert_id: Alert identifier.
         *         user: Current user.
         *         store: Application store.
         *         audit: Audit logger.
         */
        post: operations["ack_alert_api_v1_alerts__alert_id__ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description List audit entries.
         *
         *     Args:
         *         _: Current admin with verified TOTP.
         *         store: Application store.
         *         limit: Page size.
         *         offset: Page offset.
         *
         *     Returns:
         *         Paginated audit entries.
         */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup Totp
         * @description Create or return a TOTP secret for the current user.
         *
         *     Args:
         *         user: Current user.
         *         store: Application store.
         *         totp: TOTP service.
         *
         *     Returns:
         *         TOTP setup data.
         */
        post: operations["setup_totp_api_v1_auth_2fa_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/2fa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Totp
         * @description Verify TOTP for the current user.
         *
         *     Args:
         *         payload: TOTP code payload.
         *         user: Current user.
         *         store: Application store.
         *         totp: TOTP service.
         *
         *     Returns:
         *         Updated public user.
         */
        post: operations["verify_totp_api_v1_auth_2fa_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user and set secure cookies.
         *
         *     Args:
         *         payload: Login payload.
         *         response: FastAPI response.
         *         store: Application store.
         *         passwords: Password service.
         *         csrf: CSRF service.
         *         tokens: Token service.
         *         settings: Runtime settings.
         *
         *     Returns:
         *         Public user and CSRF token.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Clear browser session cookies and record a logout audit event.
         *
         *     Args:
         *         response: FastAPI response.
         *         user: Current authenticated user.
         *         audit: Audit logger.
         *         settings: Runtime settings.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Refresh an authenticated browser session.
         *
         *     Args:
         *         request: FastAPI request.
         *         response: FastAPI response.
         *         store: Application store.
         *         csrf: CSRF service.
         *         tokens: Token service.
         *         settings: Runtime settings.
         *
         *     Returns:
         *         Public user and new CSRF token.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Register the first admin or an admin-created user.
         *
         *     Args:
         *         payload: Registration payload.
         *         request: FastAPI request.
         *         store: Application store.
         *         passwords: Password service.
         *         tokens: Token service.
         *
         *     Returns:
         *         Created public user.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Clients
         * @description List observed client devices.
         *
         *     Args:
         *         _: Current user.
         *         store: Application store.
         *         limit: Page size.
         *         offset: Page offset.
         *
         *     Returns:
         *         Paginated client list.
         */
        get: operations["list_clients_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{mac}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Client
         * @description Return one client device.
         *
         *     Args:
         *         mac: Client MAC.
         *         _: Current user.
         *         store: Application store.
         *
         *     Returns:
         *         Client device.
         */
        get: operations["get_client_api_v1_devices__mac__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engagements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Engagement
         * @description Create an engagement.
         *
         *     Args:
         *         payload: Engagement payload.
         *         _: Current admin with verified TOTP.
         *         store: Application store.
         *
         *     Returns:
         *         Created engagement.
         */
        post: operations["create_engagement_api_v1_engagements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engagements/{engagement_id}/allow-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Allow Target
         * @description Add a target to an engagement allow-list.
         *
         *     Args:
         *         engagement_id: Engagement identifier.
         *         payload: Target payload.
         *         _: Current admin with verified TOTP.
         *         store: Application store.
         */
        post: operations["allow_target_api_v1_engagements__engagement_id__allow_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Events
         * @description List events.
         *
         *     Args:
         *         _: Current user.
         *         store: Application store.
         *         limit: Page size.
         *         offset: Page offset.
         *
         *     Returns:
         *         Paginated event list.
         */
        get: operations["list_events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Event
         * @description Return one event.
         *
         *     Args:
         *         event_id: Event identifier.
         *         _: Current user.
         *         store: Application store.
         *
         *     Returns:
         *         Event.
         */
        get: operations["get_event_api_v1_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sensors
         * @description List sensors.
         *
         *     Args:
         *         _: Current admin with verified TOTP.
         *         store: Application store.
         *
         *     Returns:
         *         Paginated sensor list.
         */
        get: operations["list_sensors_api_v1_sensors_get"];
        put?: never;
        /**
         * Register Sensor
         * @description Register a sensor and issue client certificate material.
         *
         *     Args:
         *         payload: Sensor registration payload.
         *         _: Current admin with verified TOTP.
         *         store: Application store.
         *
         *     Returns:
         *         Registered sensor and certificate bundle.
         */
        post: operations["register_sensor_api_v1_sensors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/{sensor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sensor
         * @description Return one sensor.
         *
         *     Args:
         *         sensor_id: Sensor identifier.
         *         _: Current admin with verified TOTP.
         *         store: Application store.
         *
         *     Returns:
         *         Sensor record.
         */
        get: operations["get_sensor_api_v1_sensors__sensor_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/{sensor_id}/commands/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Sensor
         * @description Queue a sensor restart command.
         *
         *     Args:
         *         sensor_id: Sensor identifier.
         *         user: Current admin with verified TOTP.
         *         store: Application store.
         *         audit: Audit logger.
         *         broker: Sensor command broker.
         *
         *     Returns:
         *         Accepted command identifier.
         */
        post: operations["restart_sensor_api_v1_sensors__sensor_id__commands_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/{sensor_id}/commands/set-channel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Sensor Channel
         * @description Queue a sensor channel-change command.
         *
         *     Args:
         *         sensor_id: Sensor identifier.
         *         payload: Channel payload.
         *         user: Current admin with verified TOTP.
         *         store: Application store.
         *         audit: Audit logger.
         *         broker: Sensor command broker.
         *
         *     Returns:
         *         Accepted command identifier.
         */
        post: operations["set_sensor_channel_api_v1_sensors__sensor_id__commands_set_channel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/{sensor_id}/commands/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Sensor Agent
         * @description Queue a sensor update command.
         *
         *     Args:
         *         sensor_id: Sensor identifier.
         *         user: Current admin with verified TOTP.
         *         store: Application store.
         *         audit: Audit logger.
         *         broker: Sensor command broker.
         *
         *     Returns:
         *         Accepted command identifier.
         */
        post: operations["update_sensor_agent_api_v1_sensors__sensor_id__commands_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sensors/{sensor_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Sensor
         * @description Revoke a sensor.
         *
         *     Args:
         *         sensor_id: Sensor identifier.
         *         _: Current admin with verified TOTP.
         *         store: Application store.
         */
        post: operations["revoke_sensor_api_v1_sensors__sensor_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/acknowledgements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Authorized Operator Acknowledgement
         * @description Create the one-time authorized-operator acknowledgement.
         *
         *     Args:
         *         payload: Typed legal statement.
         *         user: Current admin with verified TOTP.
         *         store: Application store.
         *         audit: Audit logger.
         *
         *     Returns:
         *         Stored acknowledgement.
         */
        post: operations["create_authorized_operator_acknowledgement_api_v1_system_acknowledgements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return process health.
         *
         *     Returns:
         *         Health status payload.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Return Prometheus-style metrics.
         *
         *     Returns:
         *         Plain-text metrics response.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccessPoint
         * @description Normalized wireless access point snapshot.
         */
        AccessPoint: {
            /** Band */
            band?: string | null;
            /** Bssid */
            bssid: string;
            /** Channel */
            channel?: number | null;
            /** Encryption */
            encryption?: string[];
            /**
             * First Seen
             * Format: date-time
             */
            first_seen?: string;
            /** Flags */
            flags?: string[];
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen?: string;
            /** Latitude */
            latitude?: number | null;
            /** Location Source */
            location_source?: ("sensor_gps" | "wigle" | "manual") | null;
            /** Longitude */
            longitude?: number | null;
            /** Signal History */
            signal_history?: components["schemas"]["SignalSample"][];
            /**
             * Ssid
             * @default
             */
            ssid: string;
            /** Vendor Oui */
            vendor_oui?: string | null;
        };
        /**
         * AcknowledgementRequest
         * @description Authorized-operator acknowledgement request.
         */
        AcknowledgementRequest: {
            /** Statement */
            statement: string;
        };
        /**
         * Alert
         * @description Alert raised by rules or analysis workers.
         */
        Alert: {
            /** Acked At */
            acked_at?: string | null;
            /** Acked By */
            acked_by?: string | null;
            /** Id */
            id: string;
            /** Related Entities */
            related_entities?: string[];
            /** Rule Id */
            rule_id: string;
            severity: components["schemas"]["AlertSeverity"];
        };
        /**
         * AlertRule
         * @description Operator-managed alert rule evaluated against normalized events.
         */
        AlertRule: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Created By */
            created_by: string;
            /** Description */
            description?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Predicate */
            predicate: {
                [key: string]: unknown;
            };
            severity: components["schemas"]["AlertSeverity"];
        };
        /**
         * AlertRuleCreateRequest
         * @description Alert rule creation request.
         */
        AlertRuleCreateRequest: {
            /** Description */
            description?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Name */
            name: string;
            /** Predicate */
            predicate: {
                [key: string]: unknown;
            };
            severity: components["schemas"]["AlertSeverity"];
        };
        /**
         * AlertRuleUpdateRequest
         * @description Alert rule update request.
         */
        AlertRuleUpdateRequest: {
            /** Description */
            description?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Name */
            name?: string | null;
            /** Predicate */
            predicate?: {
                [key: string]: unknown;
            } | null;
            severity?: components["schemas"]["AlertSeverity"] | null;
        };
        /**
         * AlertSeverity
         * @description Alert severity buckets.
         * @enum {string}
         */
        AlertSeverity: "info" | "low" | "medium" | "high" | "critical";
        /**
         * AllowTargetRequest
         * @description Allow-list target request.
         */
        AllowTargetRequest: {
            kind: components["schemas"]["TargetKind"];
            /** Value */
            value: string;
        };
        /** ApiPage[AccessPoint] */
        ApiPage_AccessPoint_: {
            /** Items */
            items: components["schemas"]["AccessPoint"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ApiPage[AlertRule] */
        ApiPage_AlertRule_: {
            /** Items */
            items: components["schemas"]["AlertRule"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ApiPage[Alert] */
        ApiPage_Alert_: {
            /** Items */
            items: components["schemas"]["Alert"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ApiPage[AuditLog] */
        ApiPage_AuditLog_: {
            /** Items */
            items: components["schemas"]["AuditLog"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ApiPage[Client] */
        ApiPage_Client_: {
            /** Items */
            items: components["schemas"]["Client"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ApiPage[Event] */
        ApiPage_Event_: {
            /** Items */
            items: components["schemas"]["Event"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ApiPage[Sensor] */
        ApiPage_Sensor_: {
            /** Items */
            items: components["schemas"]["Sensor"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * AuditLog
         * @description Append-only audit log entry.
         */
        AuditLog: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /** Outcome */
            outcome: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Raw Tool Output Ref */
            raw_tool_output_ref?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Target */
            target?: {
                [key: string]: unknown;
            };
        };
        /**
         * Client
         * @description Normalized wireless client snapshot.
         */
        Client: {
            /** Associated Bssid */
            associated_bssid?: string | null;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen?: string;
            /**
             * Last Seen
             * Format: date-time
             */
            last_seen?: string;
            /** Mac */
            mac: string;
            /** Probes */
            probes?: string[];
            /** Signal History */
            signal_history?: components["schemas"]["SignalSample"][];
            /** Vendor Oui */
            vendor_oui?: string | null;
        };
        /**
         * Engagement
         * @description Engagement scope and lifecycle metadata.
         */
        Engagement: {
            /** Ended At */
            ended_at?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Scope Rules */
            scope_rules?: {
                [key: string]: unknown;
            }[];
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
        };
        /**
         * EngagementCreateRequest
         * @description Engagement creation request.
         */
        EngagementCreateRequest: {
            /** Name */
            name: string;
            /** Scope Rules */
            scope_rules?: {
                [key: string]: string;
            }[];
        };
        /**
         * Event
         * @description Append-only event record.
         */
        Event: {
            /** Id */
            id: string;
            kind: components["schemas"]["EventKind"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Sensor Id */
            sensor_id: string;
        };
        /**
         * EventKind
         * @description Normalized event kinds emitted by sensors.
         * @enum {string}
         */
        EventKind: "access_point_seen" | "client_seen" | "sensor_status" | "command_result";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description User login request.
         */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * LoginResponse
         * @description Login response payload.
         */
        LoginResponse: {
            /** Csrf Token */
            csrf_token: string;
            user: components["schemas"]["UserPublic"];
        };
        /**
         * RegisterRequest
         * @description User registration request.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Sensor
         * @description Registered sensor identity and health metadata.
         */
        Sensor: {
            /** Capabilities */
            capabilities?: components["schemas"]["SensorCapability"][];
            /** Id */
            id: string;
            /** Last Seen */
            last_seen?: string | null;
            /** Name */
            name: string;
            /**
             * Revoked
             * @default false
             */
            revoked: boolean;
            /** Tailnet Ip */
            tailnet_ip: string;
            /** Version */
            version: string;
        };
        /**
         * SensorCapability
         * @description Capabilities advertised by a sensor.
         * @enum {string}
         */
        SensorCapability: "passive_capture" | "channel_control" | "active_modules" | "rogue_ap" | "deauth" | "evil_twin" | "captive_portal" | "mitm" | "geo";
        /**
         * SensorCommandAcceptedResponse
         * @description Sensor command acceptance response.
         */
        SensorCommandAcceptedResponse: {
            /** Command Id */
            command_id: string;
        };
        /**
         * SensorRegisterRequest
         * @description Sensor registration payload.
         */
        SensorRegisterRequest: {
            /** Capabilities */
            capabilities?: components["schemas"]["SensorCapability"][];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tailnet Ip */
            tailnet_ip: string;
            /** Version */
            version: string;
        };
        /**
         * SensorRegisterResponse
         * @description Sensor registration response with one-time client material.
         */
        SensorRegisterResponse: {
            /** Ca Certificate Pem */
            ca_certificate_pem: string;
            /** Client Certificate Pem */
            client_certificate_pem: string;
            /** Client Private Key Pem */
            client_private_key_pem: string;
            sensor: components["schemas"]["Sensor"];
        };
        /**
         * SetChannelRequest
         * @description Set-channel command body.
         */
        SetChannelRequest: {
            /** Band */
            band: string;
            /** Channel */
            channel: number;
        };
        /**
         * SignalSample
         * @description Signal reading at a point in time.
         */
        SignalSample: {
            /** Rssi Dbm */
            rssi_dbm: number;
            /**
             * Seen At
             * Format: date-time
             */
            seen_at?: string;
        };
        /**
         * SystemAcknowledgement
         * @description Stored legal acknowledgement record.
         */
        SystemAcknowledgement: {
            /**
             * Accepted At
             * Format: date-time
             */
            accepted_at?: string;
            /** Accepted By */
            accepted_by: string;
            /** Kind */
            kind: string;
            /** Statement Hash */
            statement_hash: string;
        };
        /**
         * TargetKind
         * @description Target identifier kinds used by active-operation allow-lists.
         * @enum {string}
         */
        TargetKind: "bssid" | "ssid" | "client_mac";
        /**
         * TotpSetupResponse
         * @description TOTP setup response.
         */
        TotpSetupResponse: {
            /** Provisioning Uri */
            provisioning_uri: string;
            /** Secret */
            secret: string;
        };
        /**
         * TotpVerifyRequest
         * @description TOTP verification request.
         */
        TotpVerifyRequest: {
            /** Code */
            code: string;
        };
        /**
         * UserPublic
         * @description Safe user fields returned from API responses.
         */
        UserPublic: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Roles */
            roles?: string[];
            /**
             * Totp Enabled
             * @default false
             */
            totp_enabled: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_access_points_api_v1_access_points_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPage_AccessPoint_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_access_point_api_v1_access_points__bssid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bssid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessPoint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_access_point_clients_api_v1_access_points__bssid__clients_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                bssid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPage_Client_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                severity?: components["schemas"]["AlertSeverity"][] | null;
                acked?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPage_Alert_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alert_rules_api_v1_alerts_rules_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPage_AlertRule_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_rule_api_v1_alerts_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_alert_rule_api_v1_alerts_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_rule_api_v1_alerts_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_alert_api_v1_alerts__alert_id__ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPage_AuditLog_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setup_totp_api_v1_auth_2fa_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetupResponse"];
                };
            };
        };
    };
    verify_totp_api_v1_auth_2fa_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_api_v1_devices_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPage_Client_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_api_v1_devices__mac__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mac: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Client"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_engagement_api_v1_engagements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngagementCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Engagement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    allow_target_api_v1_engagements__engagement_id__allow_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                engagement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllowTargetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_api_v1_events_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPage_Event_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_v1_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sensors_api_v1_sensors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiPage_Sensor_"];
                };
            };
        };
    };
    register_sensor_api_v1_sensors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SensorRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorRegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sensor_api_v1_sensors__sensor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sensor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_sensor_api_v1_sensors__sensor_id__commands_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorCommandAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_sensor_channel_api_v1_sensors__sensor_id__commands_set_channel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetChannelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorCommandAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sensor_agent_api_v1_sensors__sensor_id__commands_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SensorCommandAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_sensor_api_v1_sensors__sensor_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sensor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_authorized_operator_acknowledgement_api_v1_system_acknowledgements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcknowledgementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemAcknowledgement"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
