# SPDX-License-Identifier: AGPL-3.0-only
"""Generate committed OpenAPI and frontend-facing TypeScript contracts."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
for path in [
    ROOT / "apps" / "backend" / "src",
    ROOT / "packages" / "shared-types" / "src",
]:
    sys.path.insert(0, str(path))

from cheeky_pony_backend.config import Settings  # noqa: E402
from cheeky_pony_backend.infra.in_memory_store import InMemoryStore  # noqa: E402
from cheeky_pony_backend.main import create_app  # noqa: E402


def main() -> None:
    """Generate OpenAPI JSON, schema JSON, and TypeScript stubs."""

    settings = Settings(env="test", use_in_memory_store=True, cookie_secure=False)
    app = create_app(settings=settings, store=InMemoryStore())
    openapi = app.openapi()
    package_dir = ROOT / "packages" / "shared-types"
    schemas_dir = package_dir / "schemas"
    schemas_dir.mkdir(parents=True, exist_ok=True)
    _write_json(schemas_dir / "openapi.json", openapi)
    _write_json(
        schemas_dir / "components.schemas.json",
        openapi.get("components", {}).get("schemas", {}),
    )
    _write_ts(package_dir / "src" / "cheeky_pony_shared" / "openapi-types.ts", openapi)


def _write_json(path: Path, payload: Any) -> None:
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )


def _write_ts(path: Path, openapi: dict[str, Any]) -> None:
    schemas = openapi.get("components", {}).get("schemas", {})
    paths = openapi.get("paths", {})
    body = [
        "/* Generated by scripts/generate-openapi-types.py. Do not edit manually. */",
        "export interface components {",
        "  schemas: {",
    ]
    for name in sorted(schemas):
        body.append(f"    {json.dumps(name)}: unknown;")
    body.extend(["  };", "}", "", "export interface paths {"])
    for path_name in sorted(paths):
        body.append(f"  {json.dumps(path_name)}: Record<string, unknown>;")
    body.extend(["}", ""])
    path.write_text("\n".join(body), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
