/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ShellRouteImport } from "./routes/_shell";
import { Route as ShellIndexRouteImport } from "./routes/_shell.index";
import { Route as ShellMapRouteImport } from "./routes/_shell.map";
import { Route as ShellEventsRouteImport } from "./routes/_shell.events";
import { Route as ShellDesignSystemRouteImport } from "./routes/_shell.design-system";
import { Route as ShellAuditRouteImport } from "./routes/_shell.audit";
import { Route as ShellSensorsIndexRouteImport } from "./routes/_shell.sensors.index";
import { Route as ShellNetworksIndexRouteImport } from "./routes/_shell.networks.index";
import { Route as ShellLabIndexRouteImport } from "./routes/_shell.lab.index";
import { Route as ShellEngagementsIndexRouteImport } from "./routes/_shell.engagements.index";
import { Route as ShellDevicesIndexRouteImport } from "./routes/_shell.devices.index";
import { Route as ShellAlertsIndexRouteImport } from "./routes/_shell.alerts.index";
import { Route as ShellSettingsUsersRouteImport } from "./routes/_shell.settings.users";
import { Route as ShellSettingsSystemRouteImport } from "./routes/_shell.settings.system";
import { Route as ShellSettingsAccountRouteImport } from "./routes/_shell.settings.account";
import { Route as ShellSettingsAboutRouteImport } from "./routes/_shell.settings.about";
import { Route as ShellSensorsSensorIdRouteImport } from "./routes/_shell.sensors.$sensorId";
import { Route as ShellNetworksEvilTwinsRouteImport } from "./routes/_shell.networks.evil-twins";
import { Route as ShellNetworksBssidRouteImport } from "./routes/_shell.networks.$bssid";
import { Route as ShellLabRogueApRouteImport } from "./routes/_shell.lab.rogue-ap";
import { Route as ShellLabMitmRouteImport } from "./routes/_shell.lab.mitm";
import { Route as ShellLabEvilTwinRouteImport } from "./routes/_shell.lab.evil-twin";
import { Route as ShellLabDeauthRouteImport } from "./routes/_shell.lab.deauth";
import { Route as ShellLabCaptivePortalRouteImport } from "./routes/_shell.lab.captive-portal";
import { Route as ShellEngagementsIdRouteImport } from "./routes/_shell.engagements.$id";
import { Route as ShellDevicesMacRouteImport } from "./routes/_shell.devices.$mac";
import { Route as ShellAlertsRulesRouteImport } from "./routes/_shell.alerts.rules";
import { Route as ShellEngagementsEngagementIdPcapsPcapIdRouteImport } from "./routes/_shell.engagements.$engagementId.pcaps.$pcapId";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ShellRoute = ShellRouteImport.update({
  id: "/_shell",
  getParentRoute: () => rootRouteImport,
} as any);
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellMapRoute = ShellMapRouteImport.update({
  id: "/map",
  path: "/map",
  getParentRoute: () => ShellRoute,
} as any);
const ShellEventsRoute = ShellEventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => ShellRoute,
} as any);
const ShellDesignSystemRoute = ShellDesignSystemRouteImport.update({
  id: "/design-system",
  path: "/design-system",
  getParentRoute: () => ShellRoute,
} as any);
const ShellAuditRoute = ShellAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => ShellRoute,
} as any);
const ShellSensorsIndexRoute = ShellSensorsIndexRouteImport.update({
  id: "/sensors/",
  path: "/sensors/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellNetworksIndexRoute = ShellNetworksIndexRouteImport.update({
  id: "/networks/",
  path: "/networks/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLabIndexRoute = ShellLabIndexRouteImport.update({
  id: "/lab/",
  path: "/lab/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellEngagementsIndexRoute = ShellEngagementsIndexRouteImport.update({
  id: "/engagements/",
  path: "/engagements/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellDevicesIndexRoute = ShellDevicesIndexRouteImport.update({
  id: "/devices/",
  path: "/devices/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellAlertsIndexRoute = ShellAlertsIndexRouteImport.update({
  id: "/alerts/",
  path: "/alerts/",
  getParentRoute: () => ShellRoute,
} as any);
const ShellSettingsUsersRoute = ShellSettingsUsersRouteImport.update({
  id: "/settings/users",
  path: "/settings/users",
  getParentRoute: () => ShellRoute,
} as any);
const ShellSettingsSystemRoute = ShellSettingsSystemRouteImport.update({
  id: "/settings/system",
  path: "/settings/system",
  getParentRoute: () => ShellRoute,
} as any);
const ShellSettingsAccountRoute = ShellSettingsAccountRouteImport.update({
  id: "/settings/account",
  path: "/settings/account",
  getParentRoute: () => ShellRoute,
} as any);
const ShellSettingsAboutRoute = ShellSettingsAboutRouteImport.update({
  id: "/settings/about",
  path: "/settings/about",
  getParentRoute: () => ShellRoute,
} as any);
const ShellSensorsSensorIdRoute = ShellSensorsSensorIdRouteImport.update({
  id: "/sensors/$sensorId",
  path: "/sensors/$sensorId",
  getParentRoute: () => ShellRoute,
} as any);
const ShellNetworksEvilTwinsRoute = ShellNetworksEvilTwinsRouteImport.update({
  id: "/networks/evil-twins",
  path: "/networks/evil-twins",
  getParentRoute: () => ShellRoute,
} as any);
const ShellNetworksBssidRoute = ShellNetworksBssidRouteImport.update({
  id: "/networks/$bssid",
  path: "/networks/$bssid",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLabRogueApRoute = ShellLabRogueApRouteImport.update({
  id: "/lab/rogue-ap",
  path: "/lab/rogue-ap",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLabMitmRoute = ShellLabMitmRouteImport.update({
  id: "/lab/mitm",
  path: "/lab/mitm",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLabEvilTwinRoute = ShellLabEvilTwinRouteImport.update({
  id: "/lab/evil-twin",
  path: "/lab/evil-twin",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLabDeauthRoute = ShellLabDeauthRouteImport.update({
  id: "/lab/deauth",
  path: "/lab/deauth",
  getParentRoute: () => ShellRoute,
} as any);
const ShellLabCaptivePortalRoute = ShellLabCaptivePortalRouteImport.update({
  id: "/lab/captive-portal",
  path: "/lab/captive-portal",
  getParentRoute: () => ShellRoute,
} as any);
const ShellEngagementsIdRoute = ShellEngagementsIdRouteImport.update({
  id: "/engagements/$id",
  path: "/engagements/$id",
  getParentRoute: () => ShellRoute,
} as any);
const ShellDevicesMacRoute = ShellDevicesMacRouteImport.update({
  id: "/devices/$mac",
  path: "/devices/$mac",
  getParentRoute: () => ShellRoute,
} as any);
const ShellAlertsRulesRoute = ShellAlertsRulesRouteImport.update({
  id: "/alerts/rules",
  path: "/alerts/rules",
  getParentRoute: () => ShellRoute,
} as any);
const ShellEngagementsEngagementIdPcapsPcapIdRoute =
  ShellEngagementsEngagementIdPcapsPcapIdRouteImport.update({
    id: "/engagements/$engagementId/pcaps/$pcapId",
    path: "/engagements/$engagementId/pcaps/$pcapId",
    getParentRoute: () => ShellRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof ShellIndexRoute;
  "/login": typeof LoginRoute;
  "/audit": typeof ShellAuditRoute;
  "/design-system": typeof ShellDesignSystemRoute;
  "/events": typeof ShellEventsRoute;
  "/map": typeof ShellMapRoute;
  "/alerts/rules": typeof ShellAlertsRulesRoute;
  "/devices/$mac": typeof ShellDevicesMacRoute;
  "/engagements/$id": typeof ShellEngagementsIdRoute;
  "/lab/captive-portal": typeof ShellLabCaptivePortalRoute;
  "/lab/deauth": typeof ShellLabDeauthRoute;
  "/lab/evil-twin": typeof ShellLabEvilTwinRoute;
  "/lab/mitm": typeof ShellLabMitmRoute;
  "/lab/rogue-ap": typeof ShellLabRogueApRoute;
  "/networks/$bssid": typeof ShellNetworksBssidRoute;
  "/networks/evil-twins": typeof ShellNetworksEvilTwinsRoute;
  "/sensors/$sensorId": typeof ShellSensorsSensorIdRoute;
  "/settings/about": typeof ShellSettingsAboutRoute;
  "/settings/account": typeof ShellSettingsAccountRoute;
  "/settings/system": typeof ShellSettingsSystemRoute;
  "/settings/users": typeof ShellSettingsUsersRoute;
  "/alerts/": typeof ShellAlertsIndexRoute;
  "/devices/": typeof ShellDevicesIndexRoute;
  "/engagements/": typeof ShellEngagementsIndexRoute;
  "/lab/": typeof ShellLabIndexRoute;
  "/networks/": typeof ShellNetworksIndexRoute;
  "/sensors/": typeof ShellSensorsIndexRoute;
  "/engagements/$engagementId/pcaps/$pcapId": typeof ShellEngagementsEngagementIdPcapsPcapIdRoute;
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute;
  "/audit": typeof ShellAuditRoute;
  "/design-system": typeof ShellDesignSystemRoute;
  "/events": typeof ShellEventsRoute;
  "/map": typeof ShellMapRoute;
  "/": typeof ShellIndexRoute;
  "/alerts/rules": typeof ShellAlertsRulesRoute;
  "/devices/$mac": typeof ShellDevicesMacRoute;
  "/engagements/$id": typeof ShellEngagementsIdRoute;
  "/lab/captive-portal": typeof ShellLabCaptivePortalRoute;
  "/lab/deauth": typeof ShellLabDeauthRoute;
  "/lab/evil-twin": typeof ShellLabEvilTwinRoute;
  "/lab/mitm": typeof ShellLabMitmRoute;
  "/lab/rogue-ap": typeof ShellLabRogueApRoute;
  "/networks/$bssid": typeof ShellNetworksBssidRoute;
  "/networks/evil-twins": typeof ShellNetworksEvilTwinsRoute;
  "/sensors/$sensorId": typeof ShellSensorsSensorIdRoute;
  "/settings/about": typeof ShellSettingsAboutRoute;
  "/settings/account": typeof ShellSettingsAccountRoute;
  "/settings/system": typeof ShellSettingsSystemRoute;
  "/settings/users": typeof ShellSettingsUsersRoute;
  "/alerts": typeof ShellAlertsIndexRoute;
  "/devices": typeof ShellDevicesIndexRoute;
  "/engagements": typeof ShellEngagementsIndexRoute;
  "/lab": typeof ShellLabIndexRoute;
  "/networks": typeof ShellNetworksIndexRoute;
  "/sensors": typeof ShellSensorsIndexRoute;
  "/engagements/$engagementId/pcaps/$pcapId": typeof ShellEngagementsEngagementIdPcapsPcapIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_shell": typeof ShellRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_shell/audit": typeof ShellAuditRoute;
  "/_shell/design-system": typeof ShellDesignSystemRoute;
  "/_shell/events": typeof ShellEventsRoute;
  "/_shell/map": typeof ShellMapRoute;
  "/_shell/": typeof ShellIndexRoute;
  "/_shell/alerts/rules": typeof ShellAlertsRulesRoute;
  "/_shell/devices/$mac": typeof ShellDevicesMacRoute;
  "/_shell/engagements/$id": typeof ShellEngagementsIdRoute;
  "/_shell/lab/captive-portal": typeof ShellLabCaptivePortalRoute;
  "/_shell/lab/deauth": typeof ShellLabDeauthRoute;
  "/_shell/lab/evil-twin": typeof ShellLabEvilTwinRoute;
  "/_shell/lab/mitm": typeof ShellLabMitmRoute;
  "/_shell/lab/rogue-ap": typeof ShellLabRogueApRoute;
  "/_shell/networks/$bssid": typeof ShellNetworksBssidRoute;
  "/_shell/networks/evil-twins": typeof ShellNetworksEvilTwinsRoute;
  "/_shell/sensors/$sensorId": typeof ShellSensorsSensorIdRoute;
  "/_shell/settings/about": typeof ShellSettingsAboutRoute;
  "/_shell/settings/account": typeof ShellSettingsAccountRoute;
  "/_shell/settings/system": typeof ShellSettingsSystemRoute;
  "/_shell/settings/users": typeof ShellSettingsUsersRoute;
  "/_shell/alerts/": typeof ShellAlertsIndexRoute;
  "/_shell/devices/": typeof ShellDevicesIndexRoute;
  "/_shell/engagements/": typeof ShellEngagementsIndexRoute;
  "/_shell/lab/": typeof ShellLabIndexRoute;
  "/_shell/networks/": typeof ShellNetworksIndexRoute;
  "/_shell/sensors/": typeof ShellSensorsIndexRoute;
  "/_shell/engagements/$engagementId/pcaps/$pcapId": typeof ShellEngagementsEngagementIdPcapsPcapIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/audit"
    | "/design-system"
    | "/events"
    | "/map"
    | "/alerts/rules"
    | "/devices/$mac"
    | "/engagements/$id"
    | "/lab/captive-portal"
    | "/lab/deauth"
    | "/lab/evil-twin"
    | "/lab/mitm"
    | "/lab/rogue-ap"
    | "/networks/$bssid"
    | "/networks/evil-twins"
    | "/sensors/$sensorId"
    | "/settings/about"
    | "/settings/account"
    | "/settings/system"
    | "/settings/users"
    | "/alerts/"
    | "/devices/"
    | "/engagements/"
    | "/lab/"
    | "/networks/"
    | "/sensors/"
    | "/engagements/$engagementId/pcaps/$pcapId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/login"
    | "/audit"
    | "/design-system"
    | "/events"
    | "/map"
    | "/"
    | "/alerts/rules"
    | "/devices/$mac"
    | "/engagements/$id"
    | "/lab/captive-portal"
    | "/lab/deauth"
    | "/lab/evil-twin"
    | "/lab/mitm"
    | "/lab/rogue-ap"
    | "/networks/$bssid"
    | "/networks/evil-twins"
    | "/sensors/$sensorId"
    | "/settings/about"
    | "/settings/account"
    | "/settings/system"
    | "/settings/users"
    | "/alerts"
    | "/devices"
    | "/engagements"
    | "/lab"
    | "/networks"
    | "/sensors"
    | "/engagements/$engagementId/pcaps/$pcapId";
  id:
    | "__root__"
    | "/_shell"
    | "/login"
    | "/_shell/audit"
    | "/_shell/design-system"
    | "/_shell/events"
    | "/_shell/map"
    | "/_shell/"
    | "/_shell/alerts/rules"
    | "/_shell/devices/$mac"
    | "/_shell/engagements/$id"
    | "/_shell/lab/captive-portal"
    | "/_shell/lab/deauth"
    | "/_shell/lab/evil-twin"
    | "/_shell/lab/mitm"
    | "/_shell/lab/rogue-ap"
    | "/_shell/networks/$bssid"
    | "/_shell/networks/evil-twins"
    | "/_shell/sensors/$sensorId"
    | "/_shell/settings/about"
    | "/_shell/settings/account"
    | "/_shell/settings/system"
    | "/_shell/settings/users"
    | "/_shell/alerts/"
    | "/_shell/devices/"
    | "/_shell/engagements/"
    | "/_shell/lab/"
    | "/_shell/networks/"
    | "/_shell/sensors/"
    | "/_shell/engagements/$engagementId/pcaps/$pcapId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell": {
      id: "/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof ShellRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_shell/": {
      id: "/_shell/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof ShellIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/map": {
      id: "/_shell/map";
      path: "/map";
      fullPath: "/map";
      preLoaderRoute: typeof ShellMapRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/events": {
      id: "/_shell/events";
      path: "/events";
      fullPath: "/events";
      preLoaderRoute: typeof ShellEventsRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/design-system": {
      id: "/_shell/design-system";
      path: "/design-system";
      fullPath: "/design-system";
      preLoaderRoute: typeof ShellDesignSystemRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/audit": {
      id: "/_shell/audit";
      path: "/audit";
      fullPath: "/audit";
      preLoaderRoute: typeof ShellAuditRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/sensors/": {
      id: "/_shell/sensors/";
      path: "/sensors";
      fullPath: "/sensors/";
      preLoaderRoute: typeof ShellSensorsIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/networks/": {
      id: "/_shell/networks/";
      path: "/networks";
      fullPath: "/networks/";
      preLoaderRoute: typeof ShellNetworksIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/lab/": {
      id: "/_shell/lab/";
      path: "/lab";
      fullPath: "/lab/";
      preLoaderRoute: typeof ShellLabIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/engagements/": {
      id: "/_shell/engagements/";
      path: "/engagements";
      fullPath: "/engagements/";
      preLoaderRoute: typeof ShellEngagementsIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/devices/": {
      id: "/_shell/devices/";
      path: "/devices";
      fullPath: "/devices/";
      preLoaderRoute: typeof ShellDevicesIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/alerts/": {
      id: "/_shell/alerts/";
      path: "/alerts";
      fullPath: "/alerts/";
      preLoaderRoute: typeof ShellAlertsIndexRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/settings/users": {
      id: "/_shell/settings/users";
      path: "/settings/users";
      fullPath: "/settings/users";
      preLoaderRoute: typeof ShellSettingsUsersRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/settings/system": {
      id: "/_shell/settings/system";
      path: "/settings/system";
      fullPath: "/settings/system";
      preLoaderRoute: typeof ShellSettingsSystemRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/settings/account": {
      id: "/_shell/settings/account";
      path: "/settings/account";
      fullPath: "/settings/account";
      preLoaderRoute: typeof ShellSettingsAccountRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/settings/about": {
      id: "/_shell/settings/about";
      path: "/settings/about";
      fullPath: "/settings/about";
      preLoaderRoute: typeof ShellSettingsAboutRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/sensors/$sensorId": {
      id: "/_shell/sensors/$sensorId";
      path: "/sensors/$sensorId";
      fullPath: "/sensors/$sensorId";
      preLoaderRoute: typeof ShellSensorsSensorIdRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/networks/evil-twins": {
      id: "/_shell/networks/evil-twins";
      path: "/networks/evil-twins";
      fullPath: "/networks/evil-twins";
      preLoaderRoute: typeof ShellNetworksEvilTwinsRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/networks/$bssid": {
      id: "/_shell/networks/$bssid";
      path: "/networks/$bssid";
      fullPath: "/networks/$bssid";
      preLoaderRoute: typeof ShellNetworksBssidRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/lab/rogue-ap": {
      id: "/_shell/lab/rogue-ap";
      path: "/lab/rogue-ap";
      fullPath: "/lab/rogue-ap";
      preLoaderRoute: typeof ShellLabRogueApRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/lab/mitm": {
      id: "/_shell/lab/mitm";
      path: "/lab/mitm";
      fullPath: "/lab/mitm";
      preLoaderRoute: typeof ShellLabMitmRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/lab/evil-twin": {
      id: "/_shell/lab/evil-twin";
      path: "/lab/evil-twin";
      fullPath: "/lab/evil-twin";
      preLoaderRoute: typeof ShellLabEvilTwinRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/lab/deauth": {
      id: "/_shell/lab/deauth";
      path: "/lab/deauth";
      fullPath: "/lab/deauth";
      preLoaderRoute: typeof ShellLabDeauthRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/lab/captive-portal": {
      id: "/_shell/lab/captive-portal";
      path: "/lab/captive-portal";
      fullPath: "/lab/captive-portal";
      preLoaderRoute: typeof ShellLabCaptivePortalRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/engagements/$id": {
      id: "/_shell/engagements/$id";
      path: "/engagements/$id";
      fullPath: "/engagements/$id";
      preLoaderRoute: typeof ShellEngagementsIdRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/devices/$mac": {
      id: "/_shell/devices/$mac";
      path: "/devices/$mac";
      fullPath: "/devices/$mac";
      preLoaderRoute: typeof ShellDevicesMacRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/alerts/rules": {
      id: "/_shell/alerts/rules";
      path: "/alerts/rules";
      fullPath: "/alerts/rules";
      preLoaderRoute: typeof ShellAlertsRulesRouteImport;
      parentRoute: typeof ShellRoute;
    };
    "/_shell/engagements/$engagementId/pcaps/$pcapId": {
      id: "/_shell/engagements/$engagementId/pcaps/$pcapId";
      path: "/engagements/$engagementId/pcaps/$pcapId";
      fullPath: "/engagements/$engagementId/pcaps/$pcapId";
      preLoaderRoute: typeof ShellEngagementsEngagementIdPcapsPcapIdRouteImport;
      parentRoute: typeof ShellRoute;
    };
  }
}

interface ShellRouteChildren {
  ShellAuditRoute: typeof ShellAuditRoute;
  ShellDesignSystemRoute: typeof ShellDesignSystemRoute;
  ShellEventsRoute: typeof ShellEventsRoute;
  ShellMapRoute: typeof ShellMapRoute;
  ShellIndexRoute: typeof ShellIndexRoute;
  ShellAlertsRulesRoute: typeof ShellAlertsRulesRoute;
  ShellDevicesMacRoute: typeof ShellDevicesMacRoute;
  ShellEngagementsIdRoute: typeof ShellEngagementsIdRoute;
  ShellLabCaptivePortalRoute: typeof ShellLabCaptivePortalRoute;
  ShellLabDeauthRoute: typeof ShellLabDeauthRoute;
  ShellLabEvilTwinRoute: typeof ShellLabEvilTwinRoute;
  ShellLabMitmRoute: typeof ShellLabMitmRoute;
  ShellLabRogueApRoute: typeof ShellLabRogueApRoute;
  ShellNetworksBssidRoute: typeof ShellNetworksBssidRoute;
  ShellNetworksEvilTwinsRoute: typeof ShellNetworksEvilTwinsRoute;
  ShellSensorsSensorIdRoute: typeof ShellSensorsSensorIdRoute;
  ShellSettingsAboutRoute: typeof ShellSettingsAboutRoute;
  ShellSettingsAccountRoute: typeof ShellSettingsAccountRoute;
  ShellSettingsSystemRoute: typeof ShellSettingsSystemRoute;
  ShellSettingsUsersRoute: typeof ShellSettingsUsersRoute;
  ShellAlertsIndexRoute: typeof ShellAlertsIndexRoute;
  ShellDevicesIndexRoute: typeof ShellDevicesIndexRoute;
  ShellEngagementsIndexRoute: typeof ShellEngagementsIndexRoute;
  ShellLabIndexRoute: typeof ShellLabIndexRoute;
  ShellNetworksIndexRoute: typeof ShellNetworksIndexRoute;
  ShellSensorsIndexRoute: typeof ShellSensorsIndexRoute;
  ShellEngagementsEngagementIdPcapsPcapIdRoute: typeof ShellEngagementsEngagementIdPcapsPcapIdRoute;
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAuditRoute: ShellAuditRoute,
  ShellDesignSystemRoute: ShellDesignSystemRoute,
  ShellEventsRoute: ShellEventsRoute,
  ShellMapRoute: ShellMapRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellAlertsRulesRoute: ShellAlertsRulesRoute,
  ShellDevicesMacRoute: ShellDevicesMacRoute,
  ShellEngagementsIdRoute: ShellEngagementsIdRoute,
  ShellLabCaptivePortalRoute: ShellLabCaptivePortalRoute,
  ShellLabDeauthRoute: ShellLabDeauthRoute,
  ShellLabEvilTwinRoute: ShellLabEvilTwinRoute,
  ShellLabMitmRoute: ShellLabMitmRoute,
  ShellLabRogueApRoute: ShellLabRogueApRoute,
  ShellNetworksBssidRoute: ShellNetworksBssidRoute,
  ShellNetworksEvilTwinsRoute: ShellNetworksEvilTwinsRoute,
  ShellSensorsSensorIdRoute: ShellSensorsSensorIdRoute,
  ShellSettingsAboutRoute: ShellSettingsAboutRoute,
  ShellSettingsAccountRoute: ShellSettingsAccountRoute,
  ShellSettingsSystemRoute: ShellSettingsSystemRoute,
  ShellSettingsUsersRoute: ShellSettingsUsersRoute,
  ShellAlertsIndexRoute: ShellAlertsIndexRoute,
  ShellDevicesIndexRoute: ShellDevicesIndexRoute,
  ShellEngagementsIndexRoute: ShellEngagementsIndexRoute,
  ShellLabIndexRoute: ShellLabIndexRoute,
  ShellNetworksIndexRoute: ShellNetworksIndexRoute,
  ShellSensorsIndexRoute: ShellSensorsIndexRoute,
  ShellEngagementsEngagementIdPcapsPcapIdRoute:
    ShellEngagementsEngagementIdPcapsPcapIdRoute,
};

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
