import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { RelativeTime } from "@/components/domain/RelativeTime";
import { type InsightKind, useInsight, useRefreshInsight } from "@/services/api/insightQueries";

interface InsightCardProps {
  kind: InsightKind;
  entityId: string | null | undefined;
  /**
   * When true, the card renders a Refresh button that bypasses the
   * server-side cache (admin+TOTP+CSRF gated). Off by default.
   */
  allowRefresh?: boolean;
  /** Optional title override; defaults to per-kind label. */
  title?: string;
}

const KIND_TITLES: Record<InsightKind, string> = {
  alert_context: "AI alert context",
  engagement_summary: "AI engagement summary",
  ap_description: "AI access-point description",
  pcap_finding: "AI finding explanation",
};

const CONFIDENCE_TONE = {
  low: "amber",
  medium: "cyan",
  high: "green",
} as const;

const UNAVAILABLE_MESSAGE = {
  disabled: "AI insights are disabled in this deployment.",
  budget_exceeded: "AI insight budget exceeded for this period — try again later.",
  client_error:
    "The AI provider returned an error. The structured data on this page is unaffected.",
  validation_failed: "The AI response failed validation and was discarded. Try Refresh.",
};

/**
 * Single rendering surface for every LLM-generated insight. Visually
 * distinct (gradient border + Sparkles icon) so the operator can
 * always tell at a glance which prose came from an LLM vs. structured
 * data. Gracefully degrades on 503: no error toast, no broken page —
 * just a dimmed "unavailable" card with the reason.
 *
 * Refreshing bypasses the server cache (admin+TOTP+CSRF gated) and is
 * opt-in via `allowRefresh` so non-admin surfaces don't render a
 * button that would 403.
 */
export function InsightCard({
  kind,
  entityId,
  allowRefresh,
  title,
}: InsightCardProps): JSX.Element {
  const query = useInsight(kind, entityId);
  const refresh = useRefreshInsight(kind);

  const result = query.data;
  const displayTitle = title ?? KIND_TITLES[kind];

  return (
    <section
      data-testid="insight-card"
      data-insight-kind={kind}
      className="rounded-md border border-accent-violet/30 bg-gradient-to-br from-accent-violet/5 to-mode/5 p-4 text-sm"
    >
      <header className="mb-2 flex flex-wrap items-center gap-2">
        <Sparkles className="size-4 text-accent-violet" aria-hidden="true" />
        <span className="font-medium text-fg-100">{displayTitle}</span>
        {result?.insight && (
          <Badge tone={CONFIDENCE_TONE[result.insight.confidence]} outline>
            {result.insight.confidence}
          </Badge>
        )}
        <span className="flex-1" />
        {allowRefresh && entityId && (
          <Button
            variant="ghost"
            size="sm"
            onClick={() => refresh.mutate(entityId)}
            disabled={refresh.isPending}
            data-testid="insight-refresh-button"
            aria-label="Refresh insight"
          >
            {refresh.isPending ? (
              <Loader2 className="size-3 animate-spin" aria-hidden="true" />
            ) : (
              <RefreshCw className="size-3" aria-hidden="true" />
            )}
          </Button>
        )}
      </header>

      {query.isLoading ? (
        <p className="text-xs text-fg-60">Generating…</p>
      ) : query.error ? (
        <p className="text-xs text-accent-red">{query.error.message}</p>
      ) : result && !result.available ? (
        <p
          className="text-xs text-fg-60"
          data-testid="insight-unavailable"
          data-reason={result.reason}
        >
          {UNAVAILABLE_MESSAGE[result.reason ?? "client_error"]}
        </p>
      ) : result?.insight ? (
        <>
          <p className="text-sm text-fg-100" data-testid="insight-summary">
            {result.insight.summary}
          </p>
          {result.insight.bullet_points && result.insight.bullet_points.length > 0 && (
            <ul
              className="mt-2 flex flex-col gap-1 pl-4 text-xs text-fg-80"
              data-testid="insight-bullets"
            >
              {result.insight.bullet_points.map((b, i) => (
                <li key={i} className="list-disc">
                  {b}
                </li>
              ))}
            </ul>
          )}
          <footer className="mt-3 flex flex-wrap items-center gap-2 text-2xs text-fg-60">
            <span>Generated by {result.insight.model}</span>
            <span>·</span>
            <span>
              <RelativeTime value={result.insight.generated_at} />
            </span>
            {result.insight.cached && (
              <>
                <span>·</span>
                <span data-testid="insight-cached-flag">cached</span>
              </>
            )}
          </footer>
        </>
      ) : null}
    </section>
  );
}
